export const heroList = [
  { query: "bruce willis", name: "Bruce Willis" },
  { query: "tom hanks", name: "Tom Hanks" },
  { query: "robert de niro", name: "Robert De Niro" },
  { query: "jack nicholson", name: "Jack Nicholson" },
  { query: "al pacino", name: "Al Pacino" },
  { query: "anthony hopkins", name: "Anthony Hopkins" },
  { query: "clint eastwood", name: "Clint Eastwood" },
  { query: "viggo mortensen", name: "Viggo Mortensen" },
  { query: "geoffrey rush", name: "Geoffrey Rush" },
  { query: "gary oldman leon", name: "Gary Oldman" },
  { query: "godgather", name: "Marlon Brando" },
  { query: "harrison ford", name: "Harrison Ford" },
  { query: "helena bonham carter", name: "Helena Bonham Carter" },
  { query: "cate blanchett", name: "Cate Blanchett" },
  { query: "jodie foster hannibal", name: "Jodie Foster" },
  { query: "winona ryder", name: "Winona Ryder" },
  { query: "charlize theron", name: "Charlize Theron" },
  { query: "michelle pfeiffer", name: "Michelle Pfeiffer" },
  { query: "meryl streep young", name: "Meryl Streep" },
  { query: "nicole kidman movie", name: "Nicole Kidman" },
  { query: "Während Du Schliefst", name: "Sandra Bullock" },
  { query: "judi dench", name: "Judi Dench" },
  { query: "julianne moore movie", name: "Julianne Moore" },
];
