export const heroList = [
  "bruce willis",
  "tom hanks",
  "robert de niro",
  "jack nicholson",
  "al pacino",
  "anthony hopkins",
  "clint eastwood",
  "viggo mortensen",
  "goffrey rush",
  "gary oldman leon",
  "godgather",
  "harrison ford",
  "helena bonham carter",
  "cate blanchett",
  "jodie foster hannibal",
  "winona ryder",
  "charlize theron",
  "michelle pfeiffer",
  "meryl streep young",
  "nicole kidman movie",
  "sandra bullock",
  "judi dench",
  "julianne moore movie",
  "elen ripley sigourne weaver",
];
